"""
Image-to-Canvas bridge — auto-creates/updates canvas image nodes
after image generation completes.

Uses existing canvas_tools execution functions for DB operations.
"""
import re
import logging

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from models import TheaterNode, Agent
from services.canvas_tools import (
    _do_create_node,
    _do_update_node,
    _calculate_auto_position,
)

logger = logging.getLogger(__name__)

# Reuse the image markdown pattern from chats.py
_IMAGE_MD_PATTERN = re.compile(r"!\[image\]\((/api/media/[^)]+)\)")

# DB stores "image" for image nodes (frontend uses "image" as React Flow type, saved directly to DB)
_IMAGE_NODE_TYPE = "image"


async def bridge_images_to_canvas(
    response_text: str,
    theater_id: str,
    target_node_id: str | None,
    agent: Agent,
    db: AsyncSession,
) -> list[str]:
    """Extract generated images from LLM response and create/update canvas nodes.

    Args:
        response_text: Full LLM response text (may contain ![image](/api/media/...) links)
        theater_id: Theater/canvas ID
        target_node_id: If set, update this node's imageUrl (edit mode)
        agent: Agent that generated the images
        db: Async database session

    Returns:
        List of action strings for SSE events (e.g. ["create_canvas_node", "update_canvas_node"])
    """
    # Extract all image URLs from the response
    image_urls = _IMAGE_MD_PATTERN.findall(response_text)
    if not image_urls:
        return []

    actions: list[str] = []

    # Edit mode: update existing node with the first generated image
    _handlers = {
        True: lambda urls: _update_target_node(urls[0], target_node_id, theater_id, db),
        False: lambda urls: _create_image_nodes(urls, theater_id, agent, db),
    }
    handler = _handlers[bool(target_node_id)]
    actions = await handler(image_urls)

    return actions


async def _update_target_node(
    image_url: str,
    node_id: str,
    theater_id: str,
    db: AsyncSession,
) -> list[str]:
    """Update an existing canvas node's imageUrl."""
    query = select(TheaterNode).where(
        TheaterNode.id == node_id,
        TheaterNode.theater_id == theater_id,
    )
    result = await db.execute(query)
    node = result.scalar_one_or_none()

    if not node:
        logger.warning("Bridge: target node %s not found in theater %s", node_id, theater_id)
        return []

    await _do_update_node(node, {"imageUrl": image_url}, db)
    logger.info("Bridge: updated node %s imageUrl → %s", node_id, image_url)
    return ["update_canvas_node"]


async def _create_image_nodes(
    image_urls: list[str],
    theater_id: str,
    agent: Agent,
    db: AsyncSession,
) -> list[str]:
    """Create new image nodes on canvas for each generated image."""
    actions: list[str] = []

    for idx, url in enumerate(image_urls):
        data = {
            "name": f"AI Generated {idx + 1}" if len(image_urls) > 1 else "AI Generated",
            "description": f"Generated by {agent.name}",
            "imageUrl": url,
            "fitMode": "cover",
        }

        await _do_create_node(
            node_type=_IMAGE_NODE_TYPE,
            data=data,
            position_x=None,
            position_y=None,
            theater_id=theater_id,
            agent_id=agent.id,
            db=db,
        )
        actions.append("create_canvas_node")
        logger.info("Bridge: created image node for %s in theater %s", url, theater_id)

    return actions
