"""add_user_storage_device_fields_and_plan_quota

Revision ID: 087b7644a8a8
Revises: t9u0v1w2x3y4
Create Date: 2026-04-14 14:17:28.471949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087b7644a8a8'
down_revision: Union[str, None] = 't9u0v1w2x3y4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_music_tasks_id'), ['id'], unique=False)

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_quota_bytes', sa.BigInteger(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_used_bytes', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('storage_quota_bytes', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('last_device_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_os', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_browser', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_user_agent', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_user_agent')
        batch_op.drop_column('last_browser')
        batch_op.drop_column('last_os')
        batch_op.drop_column('last_device_type')
        batch_op.drop_column('storage_quota_bytes')
        batch_op.drop_column('storage_used_bytes')

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_column('storage_quota_bytes')

    with op.batch_alter_table('music_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_tasks_id'))

    # ### end Alembic commands ###
