"""add_agent_target_node_types_and_node_agent_tracking

Revision ID: 1802336702d6
Revises: m9n0o1p2q3r4
Create Date: 2026-03-24 10:13:12.304574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1802336702d6'
down_revision: Union[str, None] = 'm9n0o1p2q3r4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_node_types', sa.JSON(), server_default='[]', nullable=True))

    with op.batch_alter_table('theater_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theater_edges_id'), ['id'], unique=False)

    with op.batch_alter_table('theater_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_agent_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_theater_nodes_id'), ['id'], unique=False)
        batch_op.create_foreign_key('fk_theater_nodes_created_by_agent_id', 'agents', ['created_by_agent_id'], ['id'])

    with op.batch_alter_table('theaters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theaters_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theaters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theaters_id'))

    with op.batch_alter_table('theater_nodes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_theater_nodes_created_by_agent_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_theater_nodes_id'))
        batch_op.drop_column('created_by_agent_id')

    with op.batch_alter_table('theater_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theater_edges_id'))

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('target_node_types')

    # ### end Alembic commands ###
