"""add_user_preferences_theme_language

Revision ID: 1f5bc3b7cc86
Revises: 087b7644a8a8
Create Date: 2026-04-14 16:24:24.317490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5bc3b7cc86'
down_revision: Union[str, None] = '087b7644a8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_theme', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('preferred_theme')

    # ### end Alembic commands ###
