"""add_theater_id_to_chat_sessions

Revision ID: 2733ee5c4fd0
Revises: 4d66cc052bfb
Create Date: 2026-03-24 13:51:23.880513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2733ee5c4fd0'
down_revision: Union[str, None] = '4d66cc052bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theater_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_sessions_theater_id'), ['theater_id'], unique=False)
        batch_op.create_foreign_key('fk_chat_sessions_theater_id', 'theaters', ['theater_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_sessions_theater_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_theater_id'))
        batch_op.drop_column('theater_id')

    # ### end Alembic commands ###
