"""add_context_compaction_to_chat_sessions

Revision ID: 349404aa5c3c
Revises: r6s7t8u9v0w1
Create Date: 2026-04-04 10:38:31.326664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349404aa5c3c'
down_revision: Union[str, None] = 'r6s7t8u9v0w1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compressed_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('compressed_before_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('compressed_before_id')
        batch_op.drop_column('compressed_summary')

    # ### end Alembic commands ###
