"""add_compaction_to_admin_debug_sessions

Revision ID: 4c1a8970b23d
Revises: 349404aa5c3c
Create Date: 2026-04-04 10:41:35.933980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1a8970b23d'
down_revision: Union[str, None] = '349404aa5c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_debug_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compressed_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('compressed_before_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_debug_sessions', schema=None) as batch_op:
        batch_op.drop_column('compressed_before_id')
        batch_op.drop_column('compressed_summary')

    # ### end Alembic commands ###
