"""add_admin_debug_sessions

Revision ID: 4d66cc052bfb
Revises: 1802336702d6
Create Date: 2026-03-24 12:42:31.654138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d66cc052bfb'
down_revision: Union[str, None] = '1802336702d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_debug_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_debug_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_debug_sessions_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_debug_sessions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_debug_sessions_id'), ['id'], unique=False)

    op.create_table('admin_debug_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['admin_debug_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_debug_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_debug_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_debug_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_debug_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_debug_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_admin_debug_messages_id'))

    op.drop_table('admin_debug_messages')
    with op.batch_alter_table('admin_debug_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_debug_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_admin_debug_sessions_agent_id'))
        batch_op.drop_index(batch_op.f('ix_admin_debug_sessions_admin_id'))

    op.drop_table('admin_debug_sessions')
    # ### end Alembic commands ###
