"""add_user_balance_frozen_status

Revision ID: 5f5b1c3da653
Revises: cc40fa02de06
Create Date: 2026-03-02 10:49:54.189987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5b1c3da653'
down_revision: Union[str, None] = 'cc40fa02de06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # We only want to add the new column, ignoring type changes detected by Alembic 
    # (since we handled types in previous migration but Alembic sees model definition as Float)
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_balance_frozen', sa.Boolean(), nullable=True))
        # Set default value for existing rows
        # batch_op.execute("UPDATE users SET is_balance_frozen = 0") # SQLite doesn't support execute in batch op context easily like this
        # Instead, we rely on server_default if needed, or nullable=True is fine.
    
    # Manually update existing rows to False if needed (optional since nullable=True)
    # op.execute("UPDATE users SET is_balance_frozen = 0 WHERE is_balance_frozen IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_balance_frozen')

    # ### end Alembic commands ###
