"""add_video_tasks_and_video_agent_fields

Revision ID: 7459f2d26782
Revises: d221879c21d9
Create Date: 2026-03-04 21:07:03.209572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7459f2d26782'
down_revision: Union[str, None] = 'd221879c21d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查 video_tasks 表是否已存在
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'video_tasks' not in tables:
        op.create_table('video_tasks',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('xai_task_id', sa.String(length=255), nullable=True),
            sa.Column('session_id', sa.String(length=36), nullable=True),
            sa.Column('message_id', sa.String(length=36), nullable=True),
            sa.Column('agent_id', sa.String(length=36), nullable=True),
            sa.Column('user_id', sa.String(length=36), nullable=True),
            sa.Column('video_mode', sa.String(length=20), nullable=True),
            sa.Column('prompt', sa.Text(), nullable=True),
            sa.Column('image_url', sa.String(), nullable=True),
            sa.Column('duration', sa.Integer(), nullable=True),
            sa.Column('quality', sa.String(length=10), nullable=True),
            sa.Column('aspect_ratio', sa.String(length=10), nullable=True),
            sa.Column('mode', sa.String(length=10), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.Column('result_video_url', sa.String(), nullable=True),
            sa.Column('error_message', sa.Text(), nullable=True),
            sa.Column('input_image_count', sa.Integer(), nullable=True),
            sa.Column('output_duration_seconds', sa.Float(), nullable=True),
            sa.Column('credit_cost', sa.Float(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
            sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
            sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
            sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('video_tasks', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_video_tasks_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_video_tasks_status'), ['status'], unique=False)
            batch_op.create_index(batch_op.f('ix_video_tasks_user_id'), ['user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_video_tasks_xai_task_id'), ['xai_task_id'], unique=False)

    # 检查 agents 表的列是否存在
    existing_columns = [col['name'] for col in inspector.get_columns('agents')]
    
    with op.batch_alter_table('agents', schema=None) as batch_op:
        if 'video_input_image_credit' not in existing_columns:
            batch_op.add_column(sa.Column('video_input_image_credit', sa.Float(), nullable=False, server_default='0'))
        if 'video_input_second_credit' not in existing_columns:
            batch_op.add_column(sa.Column('video_input_second_credit', sa.Float(), nullable=False, server_default='0'))
        if 'video_output_480p_credit' not in existing_columns:
            batch_op.add_column(sa.Column('video_output_480p_credit', sa.Float(), nullable=False, server_default='0'))
        if 'video_output_720p_credit' not in existing_columns:
            batch_op.add_column(sa.Column('video_output_720p_credit', sa.Float(), nullable=False, server_default='0'))

    # 检查并创建 llm_providers 的索引（如果不存在）
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('llm_providers')]
    
    with op.batch_alter_table('llm_providers', schema=None) as batch_op:
        if 'ix_llm_providers_id' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_llm_providers_id'), ['id'], unique=False)
        if 'ix_llm_providers_name' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_llm_providers_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查并删除 llm_providers 的索引（如果存在）
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('llm_providers')]
    
    with op.batch_alter_table('llm_providers', schema=None) as batch_op:
        if 'ix_llm_providers_name' in existing_indexes:
            batch_op.drop_index(batch_op.f('ix_llm_providers_name'))
        if 'ix_llm_providers_id' in existing_indexes:
            batch_op.drop_index(batch_op.f('ix_llm_providers_id'))

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('video_output_720p_credit')
        batch_op.drop_column('video_output_480p_credit')
        batch_op.drop_column('video_input_second_credit')
        batch_op.drop_column('video_input_image_credit')

    with op.batch_alter_table('video_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_tasks_xai_task_id'))
        batch_op.drop_index(batch_op.f('ix_video_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_video_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_video_tasks_id'))

    op.drop_table('video_tasks')
    # ### end Alembic commands ###
