"""migrate_credits_to_decimal_and_atomic_check

Revision ID: cc40fa02de06
Revises: k7l8m9n0o1p2
Create Date: 2026-03-02 10:17:33.651993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc40fa02de06'
down_revision: Union[str, None] = 'k7l8m9n0o1p2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _cleanup_temp_tables():
    """清理可能残留的 Alembic 临时表"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    for table in tables:
        if table.startswith('_alembic_tmp_'):
            print(f"Cleaning up residual temp table: {table}")
            op.execute(f'DROP TABLE IF EXISTS "{table}"')

def _create_assets_table_if_not_exists():
    """创建 assets 表（如果不存在）"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'assets' not in tables:
        print("Creating assets table...")
        op.create_table('assets',
            sa.Column('id', sa.String(36), nullable=False),
            sa.Column('user_id', sa.String(36), nullable=True),
            sa.Column('filename', sa.String(255), nullable=False),
            sa.Column('original_name', sa.String(255), nullable=True),
            sa.Column('file_path', sa.String(500), nullable=False),
            sa.Column('file_type', sa.String(50), nullable=True),
            sa.Column('mime_type', sa.String(100), nullable=True),
            sa.Column('size', sa.Integer(), nullable=True),
            sa.Column('width', sa.Integer(), nullable=True),
            sa.Column('height', sa.Integer(), nullable=True),
            sa.Column('duration', sa.Float(), nullable=True),
            sa.Column('metadata_json', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('assets', schema=None) as batch_op:
            batch_op.create_index('ix_assets_id', ['id'], unique=False)
            batch_op.create_index('ix_assets_user_id', ['user_id'], unique=False)

def upgrade() -> None:
    # 首先清理可能残留的临时表
    _cleanup_temp_tables()
    
    # 创建 assets 表（如果模型中有但数据库中没有）
    _create_assets_table_if_not_exists()
    
    # 1. 迁移用户表 credits 字段为 DECIMAL(18, 4)
    # 注意：SQLite 不支持直接 ALTER COLUMN 修改类型为 DECIMAL，这里使用 batch_alter_table
    # 但 SQLAlchemy 对 SQLite 的 DECIMAL 支持通常是存储为浮点或字符串。
    # 为了兼容性，我们确保它是 Float 或 Numeric，但在代码层面我们已经知道它是 Float。
    # 真正的 "DECIMAL" 迁移在 SQLite 中比较复杂，通常涉及创建新表。
    # 鉴于当前环境是开发/测试，且原类型是 Float，我们重点关注 atomic deduction 逻辑。
    # 这里我们显式地将 Float 转换为 Numeric (如果数据库支持) 或者保持 Float 但在应用层处理精度。
    # 更好的做法是：在模型定义中改为 DECIMAL，然后 Alembic 生成迁移。
    # 但由于自动生成没有检测到 Float -> Numeric 的变化（因为 Python 中 Float 和 Numeric 有时混用），
    # 我们手动添加类型转换。
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(18, 4),
               existing_nullable=False,
               server_default='0.0')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(18, 4),
               existing_nullable=False,
               server_default='0.0')

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(18, 4),
               existing_nullable=False)
        batch_op.alter_column('balance_before',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(18, 4),
               existing_nullable=False)
        batch_op.alter_column('balance_after',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(18, 4),
               existing_nullable=False)
               
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('is_leader',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('max_subtasks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'10'"))
        batch_op.alter_column('enable_auto_review',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # assets 表的外键已在 _create_assets_table_if_not_exists 中创建
    # 如果表已存在，检查是否需要添加外键
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'assets' in tables:
        # 检查外键是否已存在
        fks = inspector.get_foreign_keys('assets')
        fk_names = [fk.get('name') for fk in fks]
        if 'fk_assets_user_id' not in fk_names:
            with op.batch_alter_table('assets', schema=None) as batch_op:
                batch_op.create_foreign_key('fk_assets_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        # Drop constraint requires name, but auto-gen might not know it.
        # If this fails, we might need to inspect db. 
        # However, alembic auto-gen typically tries to recreate table in batch mode.
        # Let's try to provide a name if we can guess it, or use naming convention.
        # But 'None' here means alembic detected it but couldn't name it.
        # In batch mode, we usually recreate the table so dropping might be implicit or handled.
        # Let's see if we can just re-declare FKs.
        pass 

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_credit_transactions_admin_id', 'admins', ['admin_id'], ['id'])

    with op.batch_alter_table('story_chapters', schema=None) as batch_op:
        # The players table might not exist in reflection if it was dropped previously
        # We should just drop the constraint if it exists, or skip it.
        # But 'batch_op' tries to reflect the table.
        # The issue is that the FK points to 'players', but 'players' table might be gone or renamed.
        # When alembic reflects 'story_chapters', it sees a FK to 'players'.
        # If 'players' table doesn't exist, reflection fails.
        # We need to manually recreate the table without that FK, or try to fix the FK.
        # Since we are in batch mode (recreating table), we can redefine the FKs we want.
        # The auto-generated code tries to drop 'None' constraint which might be the one to 'players'.
        # We can try to explicitly recreate the table structure for story_chapters here.
        
        # However, to avoid reflection error on the 'players' table, we might need to bypass reflection or 
        # ensure 'players' table exists (dummy).
        # A better approach for SQLite batch migration when FK targets are missing is tricky.
        
        # Let's assume we just want to ADD the new FK to 'users'.
        # And we want to remove the old one.
        # If we can't reflect, we can't use batch_alter_table easily unless we mock the table.
        
        # Alternatively, we can define the table structure explicitly in the operation to avoid full reflection of FKs.
        # But alembic batch op usually reflects.
        
        # Let's try to just create the new FK and ignore the old one if possible? 
        # No, the old one to 'players' is what causes the error because 'players' is missing.
        
        # Hack: Create a dummy players table if it doesn't exist? No, that's messy.
        
        # Let's try to manually run SQL to fix story_chapters.
        pass
        
    # Manual fix for story_chapters to replace FK to players with FK to users
    # 1. Create new table
    op.execute("""
        CREATE TABLE story_chapters_new (
            id INTEGER NOT NULL, 
            user_id VARCHAR(36), 
            chapter_number INTEGER, 
            title VARCHAR, 
            content TEXT, 
            status VARCHAR, 
            choices JSON, 
            summary_embedding JSON, 
            world_state_snapshot JSON, 
            created_at DATETIME DEFAULT (CURRENT_TIMESTAMP), 
            PRIMARY KEY (id), 
            FOREIGN KEY(user_id) REFERENCES users (id)
        )
    """)
    # 2. Copy data
    op.execute("INSERT INTO story_chapters_new SELECT * FROM story_chapters")
    # 3. Drop old table
    op.execute("DROP TABLE story_chapters")
    # 4. Rename new table
    op.execute("ALTER TABLE story_chapters_new RENAME TO story_chapters")
    # 5. Create index
    op.create_index(op.f('ix_story_chapters_id'), 'story_chapters', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_chapters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['user_id'], ['id'])

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('balance_after',
               existing_type=sa.DECIMAL(18, 4),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('balance_before',
               existing_type=sa.DECIMAL(18, 4),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.DECIMAL(18, 4),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.DECIMAL(18, 4),
               type_=sa.FLOAT(),
               existing_nullable=False,
               server_default='0.0')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.DECIMAL(18, 4),
               type_=sa.FLOAT(),
               existing_nullable=False,
               server_default='0.0')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # assets 表在降级时可能被删除，检查是否存在
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'assets' in tables:
        with op.batch_alter_table('assets', schema=None) as batch_op:
            batch_op.drop_constraint('fk_assets_user_id', type_='foreignkey')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('enable_auto_review',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('max_subtasks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'10'"))
        batch_op.alter_column('is_leader',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
