"""add_agent_type_and_prompt_templates

Revision ID: d221879c21d9
Revises: 5f5b1c3da653
Create Date: 2026-03-04 10:45:34.450790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd221879c21d9'
down_revision: Union[str, None] = '5f5b1c3da653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 使用 try/except 跳过已存在的表
    try:
        op.create_table('prompt_templates',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('template_type', sa.String(length=50), nullable=False),
        sa.Column('agent_type', sa.String(length=20), nullable=False),
        sa.Column('system_prompt_template', sa.Text(), nullable=False),
        sa.Column('user_prompt_template', sa.Text(), nullable=True),
        sa.Column('output_schema', sa.JSON(), nullable=True),
        sa.Column('variables_schema', sa.JSON(), nullable=True),
        sa.Column('default_agent_id', sa.String(length=36), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['default_agent_id'], ['agents.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_prompt_templates_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_prompt_templates_name'), ['name'], unique=True)
            batch_op.create_index(batch_op.f('ix_prompt_templates_template_type'), ['template_type'], unique=False)
    except Exception:
        pass  # 表已存在，跳过

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.DECIMAL(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0.0'"))

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_type', sa.String(length=20), nullable=False, server_default='text'))

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DECIMAL(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('balance_before',
               existing_type=sa.DECIMAL(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('balance_after',
               existing_type=sa.DECIMAL(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.DECIMAL(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0.0'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=18, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text("'0.0'"))

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.alter_column('balance_after',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=18, scale=4),
               existing_nullable=False)
        batch_op.alter_column('balance_before',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=18, scale=4),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=18, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('agent_type')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=18, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text("'0.0'"))

    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_template_type'))
        batch_op.drop_index(batch_op.f('ix_prompt_templates_name'))
        batch_op.drop_index(batch_op.f('ix_prompt_templates_id'))

    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
