"""add max_tool_rounds to agent

Revision ID: s8t9u0v1w2x3
Revises: r6s7t8u9v0w1
Create Date: 2025-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 's8t9u0v1w2x3'
down_revision = 'f80dfa19ec6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('max_tool_rounds', sa.Integer(), nullable=True, server_default='100'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'max_tool_rounds')
    # ### end Alembic commands ###
